"""full_initial_schema

Revision ID: 8ff9bcf343f7
Revises: 
Create Date: 2026-03-11 12:38:44.334907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff9bcf343f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_id'), ['id'], unique=False)

    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', name='playerstatus'), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('conservative_rating', sa.Float(), nullable=False),
    sa.Column('total_goals', sa.Integer(), nullable=False),
    sa.Column('total_assists', sa.Integer(), nullable=False),
    sa.Column('total_plus_minus', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_username'), ['username'], unique=True)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('internal', 'external', name='matchtype'), nullable=False),
    sa.Column('game_type', sa.Enum('ultimate', 'goal', name='gametype'), nullable=False),
    sa.Column('data_level', sa.Integer(), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=False),
    sa.Column('team_b_score', sa.Integer(), nullable=False),
    sa.Column('opponent_strength', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', name='matchstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['player.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_match_date'), ['match_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_team_id'), ['team_id'], unique=False)

    op.create_table('player_chemistry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.Integer(), nullable=False),
    sa.Column('player_b_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('co_matches', sa.Integer(), nullable=False),
    sa.Column('co_wins', sa.Integer(), nullable=False),
    sa.Column('chemistry_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_a_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_a_id', 'player_b_id', 'team_id', name='uq_chemistry')
    )
    with op.batch_alter_table('player_chemistry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_chemistry_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_chemistry_team_id'), ['team_id'], unique=False)

    op.create_table('team_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_post_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_post_team_id'), ['team_id'], unique=False)

    op.create_table('team_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('composite_ts_weight', sa.Float(), nullable=False),
    sa.Column('composite_perf_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    with op.batch_alter_table('team_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_settings_id'), ['id'], unique=False)

    op.create_table('match_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('goal', 'assist', 'defense', 'halftime', 'start', 'end', name='eventtype'), nullable=False),
    sa.Column('team_side', sa.Enum('A', 'B', name='teamside'), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_id', sa.Integer(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assist_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_event_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_event_match_id'), ['match_id'], unique=False)

    op.create_table('match_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_side', sa.Enum('A', 'B', name='teamside'), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('is_mvp', sa.Boolean(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('mu_before', sa.Float(), nullable=False),
    sa.Column('sigma_before', sa.Float(), nullable=False),
    sa.Column('mu_after', sa.Float(), nullable=True),
    sa.Column('sigma_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player')
    )
    with op.batch_alter_table('match_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_player_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_player_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_player_player_id'), ['player_id'], unique=False)

    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('mu_before', sa.Float(), nullable=False),
    sa.Column('sigma_before', sa.Float(), nullable=False),
    sa.Column('mu_after', sa.Float(), nullable=False),
    sa.Column('sigma_after', sa.Float(), nullable=False),
    sa.Column('conservative_before', sa.Float(), nullable=False),
    sa.Column('conservative_after', sa.Float(), nullable=False),
    sa.Column('delta_mu', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('operated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['operated_by'], ['player.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_history_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_history_player_id'))
        batch_op.drop_index(batch_op.f('ix_rating_history_id'))

    op.drop_table('rating_history')
    with op.batch_alter_table('match_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_player_player_id'))
        batch_op.drop_index(batch_op.f('ix_match_player_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_player_id'))

    op.drop_table('match_player')
    with op.batch_alter_table('match_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_event_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_event_id'))

    op.drop_table('match_event')
    with op.batch_alter_table('team_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_settings_id'))

    op.drop_table('team_settings')
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_post_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_post_id'))

    op.drop_table('team_post')
    with op.batch_alter_table('player_chemistry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_chemistry_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_chemistry_id'))

    op.drop_table('player_chemistry')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_team_id'))
        batch_op.drop_index(batch_op.f('ix_match_match_date'))
        batch_op.drop_index(batch_op.f('ix_match_id'))

    op.drop_table('match')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_username'))
        batch_op.drop_index(batch_op.f('ix_player_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_id'))

    op.drop_table('player')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_id'))

    op.drop_table('team')
    # ### end Alembic commands ###