"""add_player_email_reset_token

Revision ID: b0aab7dedf9f
Revises: 3a754045f56a
Create Date: 2026-03-11 15:21:13.528984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aab7dedf9f'
down_revision: Union[str, None] = '3a754045f56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_reset_token'))
        batch_op.drop_index(batch_op.f('ix_player_email'))
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('email')

    # ### end Alembic commands ###