"""add_combo_count_to_player_chemistry

Revision ID: 5b2753d24609
Revises: b0aab7dedf9f
Create Date: 2026-03-11 15:50:31.570197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2753d24609'
down_revision: Union[str, None] = 'b0aab7dedf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_chemistry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combo_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_chemistry', schema=None) as batch_op:
        batch_op.drop_column('combo_count')

    # ### end Alembic commands ###