"""add_schedule_tables

Revision ID: 433c4fa5cec4
Revises: 20260320_live_draft
Create Date: 2026-04-10 10:05:29.590808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433c4fa5cec4'
down_revision: Union[str, None] = '20260320_live_draft'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.Enum('game', 'training', 'internal', 'other', name='scheduleeventtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='scheduleeventstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('linked_match_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['player.id'], ),
    sa.ForeignKeyConstraint(['linked_match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_event_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_event_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_event_team_id'), ['team_id'], unique=False)

    op.create_table('schedule_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('yes', 'no', 'leave', 'sdl', name='attendancestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_event.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', name='uq_attendance_event_player')
    )
    with op.batch_alter_table('schedule_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_attendance_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_attendance_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_attendance_player_id'), ['player_id'], unique=False)

    op.create_table('schedule_line_division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('division_method', sa.Enum('auto_balanced', 'auto_strong_to_weak', 'manual', name='divisionmethod'), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['schedule_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('schedule_line_division', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_line_division_id'), ['id'], unique=False)

    op.create_table('schedule_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.String(length=50), nullable=False),
    sa.Column('line_type', sa.Enum('o_line', 'd_line', 'line', name='linetype'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['schedule_line_division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_line', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_line_div_id', ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_line_id'), ['id'], unique=False)

    op.create_table('schedule_line_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['schedule_line.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'player_id', name='uq_line_player')
    )
    with op.batch_alter_table('schedule_line_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_line_player_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_line_player_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_line_player_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_line_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_line_player_player_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_line_player_line_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_line_player_id'))

    op.drop_table('schedule_line_player')
    with op.batch_alter_table('schedule_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_line_id'))
        batch_op.drop_index('ix_schedule_line_div_id')

    op.drop_table('schedule_line')
    with op.batch_alter_table('schedule_line_division', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_line_division_id'))

    op.drop_table('schedule_line_division')
    with op.batch_alter_table('schedule_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_attendance_player_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_attendance_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_attendance_event_id'))

    op.drop_table('schedule_attendance')
    with op.batch_alter_table('schedule_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_event_team_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_event_start_date'))
        batch_op.drop_index(batch_op.f('ix_schedule_event_id'))

    op.drop_table('schedule_event')
    # ### end Alembic commands ###