"""add_missing_fk_indexes

Revision ID: 01ee54b86cfb
Revises: 20260419_add_province_city
Create Date: 2026-04-20 10:25:29.039025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ee54b86cfb'
down_revision: Union[str, None] = '20260419_add_province_city'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index('ix_rating_history_match_id', ['match_id'], unique=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index('ix_match_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_match_approved_by', ['approved_by'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index('ix_match_approved_by')
        batch_op.drop_index('ix_match_created_by')

    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_history_match_id')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_team_id'))
        batch_op.drop_index(batch_op.f('ix_external_team_name'))
        batch_op.drop_index(batch_op.f('ix_external_team_season_id'))

    op.drop_table('external_team')
    op.drop_table('ranking_api_key')
    with op.batch_alter_table('ranking_upload_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rup_batch_season_id'))

    op.drop_table('ranking_upload_batch')
    op.drop_table('ranking_admin')
    with op.batch_alter_table('tournament_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_record_batch_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_record_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_record_team_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_record_team_name'))

    op.drop_table('tournament_record')
    with op.batch_alter_table('ranking_season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_season_year'))

    op.drop_table('ranking_season')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_approved_by'), ['approved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_created_by'), ['created_by'], unique=False)
        batch_op.create_foreign_key(None, 'player', ['draft_owner_id'], ['id'])

    with op.batch_alter_table('match_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_match_event_client_event'))
        batch_op.create_unique_constraint('uq_match_event_client_event', ['match_id', 'client_event_id'])
        batch_op.drop_index(batch_op.f('uq_match_event_seq'))
        batch_op.create_unique_constraint('uq_match_event_seq', ['match_id', 'seq'])
        batch_op.create_foreign_key(None, 'player', ['created_by'], ['id'])

    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_history_match_id'), ['match_id'], unique=False)

    with op.batch_alter_table('schedule_line', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_line_div_id', ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_line_id'), ['id'], unique=False)

    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_post_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(None, 'team_post', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_team_post_parent_id'))

    with op.batch_alter_table('schedule_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_line_id'))
        batch_op.drop_index('ix_schedule_line_div_id')

    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_history_match_id'))

    with op.batch_alter_table('match_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_match_event_seq', type_='unique')
        batch_op.create_index(batch_op.f('uq_match_event_seq'), ['match_id', 'seq'], unique=1)
        batch_op.drop_constraint('uq_match_event_client_event', type_='unique')
        batch_op.create_index(batch_op.f('uq_match_event_client_event'), ['match_id', 'client_event_id'], unique=1)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_match_created_by'))
        batch_op.drop_index(batch_op.f('ix_match_approved_by'))

    op.create_table('ranking_season',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_season_year'), ['year'], unique=False)

    op.create_table('tournament_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tournament_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), nullable=False),
    sa.Column('wins', sa.INTEGER(), nullable=False),
    sa.Column('losses', sa.INTEGER(), nullable=False),
    sa.Column('draws', sa.INTEGER(), nullable=False),
    sa.Column('forfeits', sa.INTEGER(), nullable=False),
    sa.Column('total_games', sa.INTEGER(), nullable=False),
    sa.Column('win_rate', sa.FLOAT(), nullable=False),
    sa.Column('points_scored', sa.INTEGER(), nullable=False),
    sa.Column('points_conceded', sa.INTEGER(), nullable=False),
    sa.Column('pool', sa.VARCHAR(length=10), nullable=False),
    sa.Column('final_rank', sa.INTEGER(), nullable=False),
    sa.Column('computed_score', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ranking_upload_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['external_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_record_team_name'), ['team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_record_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_record_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_record_batch_id'), ['batch_id'], unique=False)

    op.create_table('ranking_admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ranking_upload_batch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('record_count', sa.INTEGER(), nullable=False),
    sa.Column('exported_at', sa.VARCHAR(length=50), nullable=True),
    sa.Column('raw_payload', sa.TEXT(), nullable=True),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_upload_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rup_batch_season_id'), ['season_id'], unique=False)

    op.create_table('ranking_api_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=10), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('external_team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('prev_rank', sa.INTEGER(), nullable=False),
    sa.Column('rank_change', sa.INTEGER(), nullable=False),
    sa.Column('total_score', sa.FLOAT(), nullable=False),
    sa.Column('avg_score', sa.FLOAT(), nullable=False),
    sa.Column('tournament_count', sa.INTEGER(), nullable=False),
    sa.Column('wins', sa.INTEGER(), nullable=False),
    sa.Column('losses', sa.INTEGER(), nullable=False),
    sa.Column('draws', sa.INTEGER(), nullable=False),
    sa.Column('forfeits', sa.INTEGER(), nullable=False),
    sa.Column('total_games', sa.INTEGER(), nullable=False),
    sa.Column('win_rate', sa.FLOAT(), nullable=False),
    sa.Column('points_scored', sa.INTEGER(), nullable=False),
    sa.Column('points_conceded', sa.INTEGER(), nullable=False),
    sa.Column('net_points', sa.INTEGER(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.Column('province', sa.VARCHAR(length=20), nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['ranking_season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'season_id', name=op.f('uq_external_team_name_season'))
    )
    with op.batch_alter_table('external_team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_team_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_team_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_team_id'), ['id'], unique=False)

    # ### end Alembic commands ###