"""add_teampost_is_deleted

Revision ID: 3a754045f56a
Revises: 8ff9bcf343f7
Create Date: 2026-03-11 14:47:23.439419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a754045f56a'
down_revision: Union[str, None] = '8ff9bcf343f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_post', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###